const data = {
    properties: [
        {
            id: 10,
            Type: "House",
            Name: "Abontire Villa",
            Price : `$1,000,000`,
            Available: "sold",
            location: "Kanvile",
            image: "https://th.bing.com/th/id/R.1af4f737dc81b8528b287e607106f0ec?rik=aKZSiAdKnv%2bDHQ&riu=http%3a%2f%2fimages.huffingtonpost.com%2f2015-04-01-1427911045-9997998-Penthouse_2.jpeg&ehk=qaqRUIFRrCrsbW%2bRTcbbh7aNpGCqf9sLfZetv9a%2fdWo%3d&risl=&pid=ImgRaw&r=0",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            bedroom_Number: 2,
            bathroom_Number: 2,
            garage_Number: 1,
            sqft: "1,500",
            lot_Size: "1,500",
            year_Built: "2018",
            year_Renovated: "2018",
            garage_Size: "1,500",
            basement_Size: "1,500",
            pool_Size: "1,500",
            toilet_Number: 2,
            region:"Northern Region",
            district: "Tamale Metro",
            date_added: "2018-01-01",
            date_update: null
        },
        {
            id: 1,
            Type: "House",
            Name: "Abontire Villa",
            Price : `$1,000,000`,
            Available: "sold",
            location: "Kanvile",
            image: "https://th.bing.com/th/id/R.1af4f737dc81b8528b287e607106f0ec?rik=aKZSiAdKnv%2bDHQ&riu=http%3a%2f%2fimages.huffingtonpost.com%2f2015-04-01-1427911045-9997998-Penthouse_2.jpeg&ehk=qaqRUIFRrCrsbW%2bRTcbbh7aNpGCqf9sLfZetv9a%2fdWo%3d&risl=&pid=ImgRaw&r=0",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            bedroom_Number: 2,
            bathroom_Number: 2,
            garage_Number: 1,
            sqft: "1,500",
            lot_Size: "1,500",
            year_Built: "2018",
            year_Renovated: "2018",
            garage_Size: "1,500",
            basement_Size: "1,500",
            pool_Size: "1,500",
            toilet_Number: 2,
            region:"Northern Region",
            district: "Tamale Metro",
            date_added: "2018-01-01",
            date_update: null
        },
        {
            id: 2,
            Type: "Semi-detached Bagulows",
            Name: "Abontire Villa",
            Price : `$1,000,000`,
            Available: "sold",
            location: "Kanvile",
            image: "https://th.bing.com/th/id/R.1af4f737dc81b8528b287e607106f0ec?rik=aKZSiAdKnv%2bDHQ&riu=http%3a%2f%2fimages.huffingtonpost.com%2f2015-04-01-1427911045-9997998-Penthouse_2.jpeg&ehk=qaqRUIFRrCrsbW%2bRTcbbh7aNpGCqf9sLfZetv9a%2fdWo%3d&risl=&pid=ImgRaw&r=0",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            bedroom_Number: 2,
            bathroom_Number: 2,
            garage_Number: 1,
            sqft: "1,500",
            lot_Size: "1,500",
            year_Built: "2018",
            year_Renovated: "2018",
            garage_Size: "1,500",
            basement_Size: "1,500",
            pool_Size: "1,500",
            toilet_Number: 2,
            region:"Northern Region",
            district: "Tamale Metro",
            date_added: "2018-01-01",
            date_update: null
        }
        , {
            id: 3,
            Type: "Penthouse",
            Name: "Abontire Villa",
            Price : `$1,000,000`,
            Available: "sold",
            location: "Kanvile",
            image: "https://th.bing.com/th/id/R.1af4f737dc81b8528b287e607106f0ec?rik=aKZSiAdKnv%2bDHQ&riu=http%3a%2f%2fimages.huffingtonpost.com%2f2015-04-01-1427911045-9997998-Penthouse_2.jpeg&ehk=qaqRUIFRrCrsbW%2bRTcbbh7aNpGCqf9sLfZetv9a%2fdWo%3d&risl=&pid=ImgRaw&r=0",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            bedroom_Number: 2,
            bathroom_Number: 2,
            garage_Number: 1,
            sqft: "1,500",
            lot_Size: "1,500",
            year_Built: "2018",
            year_Renovated: "2018",
            garage_Size: "1,500",
            basement_Size: "1,500",
            pool_Size: "1,500",
            toilet_Number: 2,
            region:"Northern Region",
            district: "Tamale Metro",
            date_added: "2018-01-01",
            date_update: null
        }
        , {
            id: 4,
            Type: "House",
            Name: "Abontire Villa",
            Price : `$1,000,000`,
            Available: "sold",
            location: "Kanvile",
            image: "https://th.bing.com/th/id/R.1af4f737dc81b8528b287e607106f0ec?rik=aKZSiAdKnv%2bDHQ&riu=http%3a%2f%2fimages.huffingtonpost.com%2f2015-04-01-1427911045-9997998-Penthouse_2.jpeg&ehk=qaqRUIFRrCrsbW%2bRTcbbh7aNpGCqf9sLfZetv9a%2fdWo%3d&risl=&pid=ImgRaw&r=0",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            bedroom_Number: 2,
            bathroom_Number: 2,
            garage_Number: 1,
            sqft: "1,500",
            lot_Size: "1,500",
            year_Built: "2018",
            year_Renovated: "2018",
            garage_Size: "1,500",
            basement_Size: "1,500",
            pool_Size: "1,500",
            toilet_Number: 2,
            region:"Northern Region",
            district: "Tamale Metro",
            date_added: "2018-01-01",
            date_update: null
        },
        {
            id: 5,
            Type: "compound House",
            Name: "Abontire Villa",
            Price : `$1,000,000`,
            Available: "sold",
            location: "Kanvile",
            image: "https://th.bing.com/th/id/R.1af4f737dc81b8528b287e607106f0ec?rik=aKZSiAdKnv%2bDHQ&riu=http%3a%2f%2fimages.huffingtonpost.com%2f2015-04-01-1427911045-9997998-Penthouse_2.jpeg&ehk=qaqRUIFRrCrsbW%2bRTcbbh7aNpGCqf9sLfZetv9a%2fdWo%3d&risl=&pid=ImgRaw&r=0",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            bedroom_Number: 2,
            bathroom_Number: 2,
            garage_Number: 1,
            sqft: "1,500",
            lot_Size: "1,500",
            year_Built: "2018",
            year_Renovated: "2018",
            garage_Size: "1,500",
            basement_Size: "1,500",
            pool_Size: "1,500",
            toilet_Number: 2,
            region:"Northern Region",
            district: "Tamale Metro",
            date_added: "2018-01-01",
            date_update: null
        },
        {
            id: 6,
            Type: "House",
            Name: "Abontire Villa",
            Price : `$1,000,000`,
            Available: "sold",
            location: "Kanvile",
            image: "https://th.bing.com/th/id/R.1af4f737dc81b8528b287e607106f0ec?rik=aKZSiAdKnv%2bDHQ&riu=http%3a%2f%2fimages.huffingtonpost.com%2f2015-04-01-1427911045-9997998-Penthouse_2.jpeg&ehk=qaqRUIFRrCrsbW%2bRTcbbh7aNpGCqf9sLfZetv9a%2fdWo%3d&risl=&pid=ImgRaw&r=0",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            bedroom_Number: 2,
            bathroom_Number: 2,
            garage_Number: 1,
            sqft: "1,500",
            lot_Size: "1,500",
            year_Built: "2018",
            year_Renovated: "2018",
            garage_Size: "1,500",
            basement_Size: "1,500",
            pool_Size: "1,500",
            toilet_Number: 2,
            region:"Northern Region",
            district: "Tamale Metro",
            date_added: "2018-01-01",
            date_update: null
        },
        {
            id: 7,
            Type: "House",
            Name: "Abontire Villa",
            Price : `$1,000,000`,
            Available: "sold",
            location: "Kanvile",
            image: "https://th.bing.com/th/id/R.1af4f737dc81b8528b287e607106f0ec?rik=aKZSiAdKnv%2bDHQ&riu=http%3a%2f%2fimages.huffingtonpost.com%2f2015-04-01-1427911045-9997998-Penthouse_2.jpeg&ehk=qaqRUIFRrCrsbW%2bRTcbbh7aNpGCqf9sLfZetv9a%2fdWo%3d&risl=&pid=ImgRaw&r=0",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            bedroom_Number: 2,
            bathroom_Number: 2,
            garage_Number: 1,
            sqft: "1,500",
            lot_Size: "1,500",
            year_Built: "2018",
            year_Renovated: "2018",
            garage_Size: "1,500",
            basement_Size: "1,500",
            pool_Size: "1,500",
            toilet_Number: 2,
            region:"Northern Region",
            district: "Tamale Metro",
            date_added: "2018-01-01",
            date_update: null
        },
        {
            id: 8,
            Type: "House",
            Name: "Abontire Villa",
            Price : `$1,000,000`,
            Available: "sold",
            location: "Kanvile",
            image: "https://th.bing.com/th/id/R.1af4f737dc81b8528b287e607106f0ec?rik=aKZSiAdKnv%2bDHQ&riu=http%3a%2f%2fimages.huffingtonpost.com%2f2015-04-01-1427911045-9997998-Penthouse_2.jpeg&ehk=qaqRUIFRrCrsbW%2bRTcbbh7aNpGCqf9sLfZetv9a%2fdWo%3d&risl=&pid=ImgRaw&r=0",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            bedroom_Number: 2,
            bathroom_Number: 2,
            garage_Number: 1,
            sqft: "1,500",
            lot_Size: "1,500",
            year_Built: "2018",
            year_Renovated: "2018",
            garage_Size: "1,500",
            basement_Size: "1,500",
            pool_Size: "1,500",
            toilet_Number: 2,
            region:"Northern Region",
            district: "Tamale Metro",
            date_added: "2018-01-01",
            date_update: null
        }
    ]
}



module.exports = data;